// Most or all contents generated by AI (model glm-5.3)

//! BLIS-style blocked matrix multiplication (step-5 example).
//!
//! Computes `C = A·B` for fixed 4096×4096 `f64` matrices — all row-major, no
//! transposes — using only the crate's portable vector types: no intrinsics,
//! no runtime dispatch; the kernel relies on compiler auto-vectorization.
//!
//! The packing and register blocking follow BLIS (van Zee & van de Geijn,
//! *BLIS: A Framework for Rapidly Instancing BLAS Functionality*, 2015); the
//! blocking is measured on the development host (AMD Ryzen 9 9955HX, 16
//! Zen 5 cores, DDR5, balance power mode):
//!
//! ```text
//! rayon task grid   (MC×NC blocks of C; 2D so each task's C block stays
//!  │                 L3-resident across its PC passes)
//!  └─ PC  (KC-deep slabs; task packs its MC×KC A panel once per slab)
//!      └─ JR  (NR-wide micro-panels of the shared pre-packed B panel)
//!          └─ IR  (MR-tall micro-panels of the packed A panel)
//!              └─ micro-kernel: one MR×NR register tile × KC depth
//! ```
//!
//! Beyond the textbook nest:
//!
//! - **B is pre-packed once** ([`pack_b_shared`]) into shared read-only panels: every task reads
//!   the same panel at the same point of the nest, so L3 serves the concurrent readers.
//! - **Tasks own 2D blocks of `C`**: the block's reuse distance across PC passes fits in L3, so `C`
//!   stays cache-resident instead of round-tripping DRAM per pass. Blocks are addressed through one
//!   raw pointer (a `&mut` slice of a row-major block necessarily ranges into the neighbouring
//!   block's columns), wrapped in a `Send + Sync` newtype whose safety contract is the disjointness
//!   of the task grid.
//! - **Pages are pre-touched** before timing: hugepages are madvise-only here, so the lazily-mapped
//!   4 KiB pages of `C` and the packed `B` would otherwise fault inside the timed region.
//!
//! Register/kernel sizing targets **x86-64 AVX-512F** (asserted at startup):
//!
//! | parameter | value | budget it fits |
//! |-----------|-------|-----------------|
//! | MR × NR   | 8 × 16 | MR·NR/8 = 16 accumulator vectors, half of the 32 zmm registers (the largest register-resident auto-vectorized tile; see the `MR` doc) |
//! | KC        | 256    | B micro-panel KC·NR·8 B = 32 KiB, streamed from L2 as in BLIS's Zen configs; strict 32-KiB-L1d sizing would force KC=128, ~40 % slower end-to-end |
//! | MC        | 256    | A panel MC·KC·8 B = 512 KiB ≤ L2 |
//! | NC        | 512    | B panel KC·NC·8 B = 1 MiB; task C block MC·NC·8 B = 1 MiB, both L3-sized |
//!
//! Run on an AVX-512 machine with:
//!
//! ```sh
//! RUSTFLAGS="-C target-cpu=native" cargo run --release --example blis_matmul
//! ```
//!
//! `rayon` parallelizes the task grid; it is a dev-dependency used by this
//! example only, not a dependency of the crate. This mirrors the "Block"
//! entry of `CONTEXT.md`: cache-blocking groups of vectors are application
//! level and deliberately outside the crate's scope.

use std::time::Instant;

use lightweight_simd::f64x8;
use rayon::prelude::*;

/// Problem size: `C`, `A`, `B` are all `N×N` (fixed; every block size below
/// divides it, so there are no edge tiles).
const N: usize = 4096;

/// f64 lanes per AVX-512F register.
const LANES: usize = 8;

/// Register tile of the micro-kernel: MR rows × NR columns of `C`.
///
/// 8×16 is the largest tile the compiler keeps fully in registers for this
/// portable code — MR=16 tiles collapse ~20× (the row loop then fails to
/// unroll and the accumulators go through gather/scatter), while hand-tuned
/// kernels manage larger tiles (e.g. BLIS's 14×16 on Zen 4 / Sapphire
/// Rapids f64) by hand-allocated registers.
const MR: usize = 8;
const NR: usize = 2 * LANES;

/// Depth block. The B micro-panel reused across the IR loop is KC·NR·8 B
/// = 32 KiB, streamed from L2 as in BLIS's Zen configurations; a strict
/// 32 KiB L1d budget would force KC=128, measured ~40 % slower end-to-end.
const KC: usize = 256;

/// Row block: the packed A panel is MC·KC·8 B = 512 KiB (L2-sized), and
/// with NC it sets the (N/MC)×(N/NC) rayon task grid.
const MC: usize = 256;

/// Column block: the packed B panel is KC·NC·8 B = 1 MiB (L3-sized); each
/// task's MC×NC block of C is likewise 1 MiB, L3-resident across its PC
/// passes.
const NC: usize = 512;

/// Number of sampled entries checked against scalar dot products afterwards.
const SAMPLES: usize = 64;

/// BLIS micro-kernel: accumulates one MR×NR tile of `C` over a KC-deep slab
/// of the packed operands,
///
/// ```text
/// C[i0..i0+MR][j0..j0+NR] += A'[0..MR][0..KC] · B'[0..KC][0..NR]
/// ```
///
/// `a` is a packed MR×KC micro-panel (row `i` at `a[i*KC..]`), `b` a packed
/// KC×NR micro-panel (depth `k` at `b[k*NR..]`), and `c` is a raw pointer to
/// element `(i0, j0)` of the row-major `C` (row stride `N`).
///
/// The raw pointer (instead of a `&mut [f64]`) is what lets the driver hand
/// out 2D blocks of `C`: a slice starting at `(i0, j0)` always ranges into
/// the neighbouring block's columns.
///
/// The 16 accumulators, the two B row vectors, and the A broadcasts fit in
/// AVX-512F's 32 zmm registers, so the C tile stays register-resident across
/// the whole KC loop — derived by the compiler from portable `f64x8` code.
///
/// # Safety
///
/// `c` must point into a valid `C` allocation such that the MR rows at
/// stride `N` and NR columns are writable for the duration of the call, and
/// no other code may write that MR×NR region concurrently.
#[inline(always)]
fn micro_kernel(a: &[f64; MR * KC], b: &[f64; KC * NR], c: *mut f64) {
    // The current C tile enters the accumulators: C starts zeroed and each
    // PC pass of the driver accumulates onto the stored partial sums.
    let mut acc = [[f64x8::zero(); NR / LANES]; MR];
    for (i, acc_row) in acc.iter_mut().enumerate() {
        // SAFETY: caller guarantees the MR×NR tile readable (see fn doc);
        // the 16-element row segment is disjoint from every other task's.
        let row = unsafe { core::slice::from_raw_parts(c.add(i * N), NR) };
        for (v, acc_v) in acc_row.iter_mut().enumerate() {
            *acc_v = f64x8::from_slice(&row[v * LANES..]);
        }
    }

    // Register-blocked FMA: per depth step, two B row vectors are loaded and
    // each A element is broadcast once and fused into both.
    for k in 0..KC {
        for v in 0..NR / LANES {
            let bv = f64x8::from_slice(&b[k * NR + v * LANES..]);
            for i in 0..MR {
                acc[i][v].fma_from(f64x8::splat(a[i * KC + k]), bv);
            }
        }
    }

    for (i, acc_row) in acc.iter().enumerate() {
        for (v, acc_v) in acc_row.iter().enumerate() {
            // SAFETY: as the load above; the lane run is within this task's
            // exclusive MR×NR tile.
            unsafe {
                core::ptr::copy_nonoverlapping(acc_v.0.as_ptr(), c.add(i * N + v * LANES), LANES);
            }
        }
    }
}

/// Packs the MC×KC panel `A[ic..ic+MC][pc..pc+KC]` into MR×KC micro-panels:
/// `pack[(ip·MR + i)·KC + k] = A[ic + ip·MR + i][pc + k]` — each panel's MR
/// rows are contiguous, so the kernel's `a[i*KC + k]` walks memory linearly.
fn pack_a(a: &[f64], ic: usize, pc: usize, pack: &mut Vec<f64>) {
    pack.clear();
    pack.reserve_exact(MC * KC);
    for r in 0..MC {
        pack.extend_from_slice(&a[(ic + r) * N + pc..][..KC]);
    }
}

/// Packs the KC×NC panel `B[pc..pc+KC][jc..jc+NC]` into KC×NR micro-panels:
/// `pack[(jp·KC + k)·NR + j] = B[pc + k][jc + jp·NR + j]` — each panel's KC
/// depth rows are contiguous, so the kernel's `b[k*NR..]` walks linearly.
/// [`pack_b_shared`] packs every panel of `B` this way, once and upfront.
fn pack_b_panel(b: &[f64], pc: usize, jc: usize, panel: &mut [f64]) {
    let mut off = 0;
    for jp in 0..NC / NR {
        for k in 0..KC {
            let src = &b[(pc + k) * N + jc + jp * NR..][..NR];
            panel[off..off + NR].copy_from_slice(src);
            off += NR;
        }
    }
}

/// One 2D block of the GEMM: `C[rb·MC..][cb·NC..] += A[rb·MC..] ·
/// B[:][cb·NC..]`, containing the PC → JR → IR loops around the
/// micro-kernel. `c` points at element `(rb·MC, cb·NC)` of the row-major
/// `C`; `b_packed` is the shared read-only pre-packed B (see
/// [`pack_b_shared`]).
///
/// The block's C stays cache-resident across its PC passes: between two
/// passes a task touches only its MC×NC tile plus one KC×NC B panel, so the
/// running tasks' tiles survive in L3.
///
/// # Safety
///
/// `c` must point at `(rb·MC, cb·NC)` of a valid `C` allocation, and no
/// other task may write this MC×NC block concurrently.
unsafe fn gemm_block(a: &[f64], b_packed: &[f64], c: *mut f64, rb: usize, cb: usize) {
    let ic = rb * MC;
    let mut a_pack = Vec::new();
    for (pci, pc) in (0..N).step_by(KC).enumerate() {
        // A panel: packed once per (block, PC) and re-read from L2 by the
        // JR sweep below.
        pack_a(a, ic, pc, &mut a_pack);
        // Shared B panel: read by every row-block task of this column strip
        // at the same point of the nest, so L3 serves the concurrent
        // readers.
        let panel = &b_packed[(pci * (N / NC) + cb) * KC * NC..][..KC * NC];
        // `as_chunks` (lengths are exact multiples) hands the micro-panels
        // to the kernel as fixed-size arrays.
        for (jp, b_mp) in panel.as_chunks::<{ KC * NR }>().0.iter().enumerate() {
            for (ip, a_mp) in a_pack.as_chunks::<{ MR * KC }>().0.iter().enumerate() {
                // IR innermost: the B micro-panel stays hot in L1d/L2
                // across it.
                // SAFETY: offsets stay inside this block's MC×NC region
                // (ip·MR < MC, jp·NR < NC) by construction.
                micro_kernel(a_mp, b_mp, unsafe { c.add(ip * MR * N + jp * NR) });
            }
        }
    }
}

/// Pre-packs all of `B` once into the panel layout [`pack_b_panel`] produces
/// (panel `(pci, jci)` at `b_packed[(pci·N/NC + jci)·KC·NC..]`). Every rayon
/// task then reads the same immutable panels at the same point of the nest —
/// one pack total instead of one per task, and the concurrent readers are
/// served by L3 instead of DRAM.
fn pack_b_shared(b: &[f64], b_packed: &mut [f64]) {
    b_packed.par_chunks_mut(KC * NC).enumerate().for_each(|(idx, panel)| {
        let (pc, jc) = ((idx / (N / NC)) * KC, (idx % (N / NC)) * NC);
        pack_b_panel(b, pc, jc, panel);
    });
}

/// Deterministic pseudo-random fill in (-1, 1) (LCG), so the sampled check
/// below is reproducible run to run.
fn fill_matrix(seed: u64) -> Vec<f64> {
    let mut state = seed;
    (0..N * N)
        .map(|_| {
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            ((state >> 11) as f64) / (1u64 << 53) as f64 * 2.0 - 1.0
        })
        .collect()
}

fn next_uniform(state: &mut u64) -> f64 {
    *state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
    ((*state >> 11) as f64) / (1u64 << 53) as f64
}

fn main() {
    // A startup assert (not `compile_error!`) keeps the example compilable
    // on any target.
    if !cfg!(all(target_arch = "x86_64", target_feature = "avx512f")) {
        panic!(
            "this example is sized and asserted for x86-64 AVX-512F; rebuild with \
             RUSTFLAGS=\"-C target-cpu=native\" (or -C target-features=+avx512f) \
             on an AVX-512 machine"
        );
    }

    println!("BLIS-style GEMM: C = A·B, {N}×{N}×{N} f64, row-major, non-transposed");
    println!(
        "blocking (AVX-512F, measured): MR×NR = {MR}×{NR} ({} zmm accumulators), \
         KC = {KC} (B micro-panel {} KiB, L2-streamed), MC = {MC} (A panel {} KiB), \
         NC = {NC} (B panel/C block {} MiB); tasks = {}×{} 2D blocks, \
         B pre-packed shared",
        MR * NR / LANES,
        KC * NR * 8 / 1024,
        MC * KC * 8 / 1024,
        KC * NC * 8 / 1024 / 1024,
        N / MC,
        N / NC,
    );

    let a = fill_matrix(0x1234_5678_9abc_def0);
    let b = fill_matrix(0x0fed_cba9_8765_4321);
    // C starts zeroed: every PC pass accumulates onto the stored tile.
    let mut c = vec![0.0; N * N];
    // B pre-packed once, shared read-only by all tasks (see pack_b_shared).
    let mut b_packed = vec![0.0; N * N];

    let threads = rayon::current_num_threads();
    // Warm the lazily-mapped pages of C and b_packed before timing
    // (hugepages are madvise-only here).
    c.par_iter_mut().for_each(|x| *x = 0.0);
    b_packed.par_iter_mut().for_each(|x| *x = 0.0);
    let t0 = Instant::now();
    pack_b_shared(&b, &mut b_packed);
    // 2D task grid; the flat index runs row-block-major within a column
    // strip, so concurrently stolen tasks share the same B panels in L3.
    struct CPtr(*mut f64);
    // SAFETY: the pointer is dereferenced only inside gemm_block, whose
    // contract assigns every task a disjoint MC×NC block of C.
    unsafe impl Send for CPtr {}
    unsafe impl Sync for CPtr {}
    impl CPtr {
        // a method, so closures capture the whole CPtr (a field access
        // would let precise captures grab the raw pointer)
        fn at(&self, rb: usize, cb: usize) -> *mut f64 {
            // SAFETY: offset arithmetic within the N×N C allocation;
            // dereferenced only under gemm_block's contract.
            unsafe { self.0.add(rb * MC * N + cb * NC) }
        }
    }
    let c_ptr = CPtr(c.as_mut_ptr());
    let rows = N / MC;
    (0..rows * (N / NC)).into_par_iter().for_each(|t| {
        let (rb, cb) = (t % rows, t / rows);
        // SAFETY: task (rb, cb) writes only rows rb·MC..(rb+1)·MC and
        // columns cb·NC..(cb+1)·NC — disjoint from every other task.
        unsafe { gemm_block(&a, &b_packed, c_ptr.at(rb, cb), rb, cb) };
    });
    let elapsed = t0.elapsed();

    let gflops = 2.0 * (N * N * N) as f64 / elapsed.as_secs_f64() / 1e9;
    println!("threads: {threads}, time: {:.1} ms, throughput: {gflops:.0} GFLOP/s", elapsed.as_secs_f64() * 1e3);

    // Spot-check sampled entries against strict-order scalar dot products;
    // the blocked summation order differs, so allow rounding-scale deviation.
    let mut state = 0x9e37_79b9_7f4a_7c15u64;
    let mut max_dev = 0.0f64;
    for _ in 0..SAMPLES {
        let i = (next_uniform(&mut state) * N as f64) as usize;
        let j = (next_uniform(&mut state) * N as f64) as usize;
        let mut dot = 0.0;
        for k in 0..N {
            dot += a[i * N + k] * b[k * N + j];
        }
        let scale = 1.0 + dot.abs();
        let dev = (c[i * N + j] - dot).abs() / scale;
        assert!(dev < 1e-9, "entry ({i},{j}) deviates: {dev:.3e} of |dot| ≈ {:.3e}", dot.abs());
        max_dev = max_dev.max(dev);
    }
    println!(
        "verification: {SAMPLES} sampled entries match scalar dot products \
         (max scaled deviation {max_dev:.2e})"
    );
}
