// Most or all contents generated by AI (model glm-5.3)

//! Lightweight generic fixed-array vector types.
//!
//! This crate provides [`Simd`], a fixed-lane vector type `Simd<T, N>` over
//! `[T; N]`, with lane-wise arithmetic (vector/vector and vector/scalar), fused
//! multiply-add, float functions, comparisons producing masks, mask selection,
//! horizontal reductions, and slice load/store — all implemented without
//! intrinsics and without runtime instruction dispatch.
//!
//! Performance relies on the compiler auto-vectorizing this portable code;
//! build with `-C target-cpu=native` (or a similar `target-cpu` setting) to
//! obtain SIMD-level efficiency. Correctness does not depend on it.
//!
//! Element categories are expressed by trait bounds rather than by distinct
//! types: arithmetic requires [`num_traits::Num`], the float functions require
//! [`num_traits::Float`], fused multiply-add requires
//! [`num_traits::MulAdd`], and bitwise operations require the element's own
//! [`core::ops`] implementations. `bool` is a valid element, and
//! `Simd<bool, N>` doubles as the mask type. The lane count `N` is an
//! arbitrary const generic.
//!
//! # Example
//!
//! ```
//! use lightweight_simd::{f64x8, Simd};
//!
//! let a = f64x8::splat(2.0);
//! let b: f64x8 = Simd::from([1.0; 8]);
//! // lane-wise fused: (a * b) * 3.0 + 0.0
//! let c = (a * b).mul_add(f64x8::splat(3.0), f64x8::zero());
//! assert_eq!(c.reduce_sum(), 48.0);
//!
//! let mask = a.simd_gt(b);
//! assert!(mask.all_true());
//! assert_eq!(mask.select(a, b).reduce_sum(), 16.0);
//! ```

#![warn(missing_docs)]
#![deny(unsafe_op_in_unsafe_fn)]

use core::ops::{Index, IndexMut};
use num_traits::{Num, One, Zero};

mod alias;
mod memory;
mod ops;
mod reduce;

pub use alias::*;

/// A fixed-length vector of `N` lanes of element type `T`.
///
/// All operations are lane-wise and implemented as plain loops over the
/// underlying `[T; N]`, so the compiler can auto-vectorize them for any
/// element type and lane count. The lane count `N` is arbitrary (powers of two
/// that fill whole SIMD registers are the sweet spot, but not required).
///
/// The type carries no enforced alignment beyond the element's natural
/// alignment; the field is public for zero-friction interoperability with
/// array code.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Copy)]
pub struct Simd<T, const N: usize>(pub [T; N]);

impl<T: Default, const N: usize> Default for Simd<T, N> {
    #[inline(always)]
    fn default() -> Self {
        Self(core::array::from_fn(|_| T::default()))
    }
}

impl<T, const N: usize> Simd<T, N> {
    /// Returns a vector whose lane `i` is `f(i)`.
    #[inline(always)]
    pub fn from_fn<F>(f: F) -> Self
    where
        F: FnMut(usize) -> T,
    {
        Self(core::array::from_fn(f))
    }

    /// Applies `f` to each lane, returning a new vector.
    ///
    /// This is the generic escape hatch for operations the crate does not
    /// provide (e.g. transcendental functions: `v.map(f64::exp)`).
    #[inline(always)]
    pub fn map<F>(self, f: F) -> Self
    where
        F: FnMut(T) -> T,
    {
        Self(self.0.map(f))
    }

    /// Returns the underlying array by reference.
    #[inline(always)]
    pub const fn as_array(&self) -> &[T; N] {
        &self.0
    }

    /// Returns the underlying array by mutable reference.
    #[inline(always)]
    pub fn as_array_mut(&mut self) -> &mut [T; N] {
        &mut self.0
    }

    /// Returns the underlying array by value.
    #[inline(always)]
    pub fn to_array(self) -> [T; N] {
        self.0
    }
}

impl<T: Copy, const N: usize> Simd<T, N> {
    /// Returns a vector with all lanes set to `val`.
    #[inline(always)]
    pub const fn splat(val: T) -> Self {
        Self([val; N])
    }

    /// Sets all lanes to `val`.
    #[inline(always)]
    pub fn fill(&mut self, val: T) {
        self.0 = [val; N];
    }

    /// Returns an uninitialized vector, intended for scratch buffers whose
    /// lanes are fully written before being read.
    ///
    /// # Safety
    ///
    /// The caller must initialize all lanes before any read. The element type
    /// must additionally admit arbitrary bit patterns (true for floats and
    /// integers; not for types with niches such as references).
    #[inline(always)]
    #[allow(clippy::uninit_assumed_init)]
    pub unsafe fn uninit() -> Self {
        // SAFETY: the caller contract requires full initialization before any
        // read of the returned value.
        unsafe { core::mem::MaybeUninit::uninit().assume_init() }
    }
}

impl<T: Zero + Copy, const N: usize> Simd<T, N> {
    /// Returns a vector with all lanes set to zero.
    #[inline(always)]
    pub fn zero() -> Self {
        Self::splat(T::zero())
    }
}

impl<T: One + Copy, const N: usize> Simd<T, N> {
    /// Returns a vector with all lanes set to one.
    #[inline(always)]
    pub fn one() -> Self {
        Self::splat(T::one())
    }
}

impl<T, const N: usize> From<[T; N]> for Simd<T, N> {
    #[inline(always)]
    fn from(array: [T; N]) -> Self {
        Self(array)
    }
}

impl<T, const N: usize> Index<usize> for Simd<T, N> {
    type Output = T;

    #[inline(always)]
    fn index(&self, index: usize) -> &Self::Output {
        &self.0[index]
    }
}

impl<T, const N: usize> IndexMut<usize> for Simd<T, N> {
    #[inline(always)]
    fn index_mut(&mut self, index: usize) -> &mut Self::Output {
        &mut self.0[index]
    }
}

impl<T: Num + Copy, const N: usize> Zero for Simd<T, N> {
    #[inline(always)]
    fn zero() -> Self {
        Self::splat(T::zero())
    }

    #[inline(always)]
    fn is_zero(&self) -> bool {
        self.0.iter().all(Zero::is_zero)
    }
}

impl<T: Num + Copy, const N: usize> One for Simd<T, N> {
    #[inline(always)]
    fn one() -> Self {
        Self::splat(T::one())
    }
}
